server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employees?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 123456

  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true

  redis:
    host: localhost
    port: 6379
    password:
    database: 10

logging:
  file:
    path: /opt/log