server:
  port: 8030
  servlet:
    context-path: /fegin-labs

spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true

management:
  endpoints:
    shutdown:
      enabled: false
    web:
      base-path: /manage
      exposure:
        include: "*"

## eureka 配置
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://test:123456@localhost:8020/eureka/
  instance:
    prefer-ip-address: true  #以IP地址注册到服务中心，相互注册使用IP地址


## fegin 配置

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
        logger-level: basic
  hystrix:
    enabled: true

ribbon:
  eureka:
    enabled: true
  connectTimeout: 3000 #单位ms,请求连接超时时间
  readTimeout: 10000 #单位ms,请求处理的超时时间
  okToRetryOnAllOperations: true #对所有操作请求都进行重试
  maxAutoRetriesNextServer: 2 #切换实例的重试次数
  maxAutoRetries: 1 #对当前实例的重试次数

