server:
  port: 8010

management:
  endpoints:
    web:
      base-path: /manage


spring:
  application:
    name: config-server-labs
  cloud:
    config:
      server:
        git:
          uri: https://github.com/halking/spring-example #配置文件所在仓库
          default-label: develop #配置文件分支
          search-paths: spring-config  #配置文件所在根目录