## server 配置
server:
  port: 8010

## actuator 配置
management:
  endpoints:
    web:
      base-path: /manage

## eureka 配置
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://test:123456@localhost:8020/eureka/
#  instance:
#    prefer-ip-address: true  #以IP地址注册到服务中心，相互注册使用IP地址

spring:
  application:
    name: config-server-labs
  cloud:
    config:
      server:
        git:
          uri: https://github.com/halking/spring-example #仓库地址
          default-label: develop #分支
          search-paths: spring-config  #目录

