server:
  servlet:
    context-path: /sample
  port: ${http.port:8082}
  tomcat:
    uri-encoding: UTF-8
spring:
  profiles:
    active: local
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,prometheus
    metrics:
      enabled: true

scheduler:
  reminder-delete:
    enabled: false


