server:
  port: 8011
  servlet:
    context-path: /config-client-labs

management:
  endpoints:
    shutdown:
      enabled: false
    web:
      base-path: /manage
      exposure:
        include: "*"

spring:
  application:
    name: config-client-labs



## eureka 配置
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://test:123456@localhost:8020/eureka/
  instance:
    prefer-ip-address: true  #以IP地址注册到服务中心，相互注册使用IP地址
