server:
  servlet:
    context-path: /sample
  port: ${http.port:8082}
  tomcat:
    uri-encoding: UTF-8
spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
scheduler:
  reminder-delete:
    enabled: false