---
spring:
  profiles: peer1
  application:
    name: eureka-server

server:
  port: 8759


eureka:
  instance:
    hostname: peer1
  client:
    #    registerWithEureka: false
    #    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer2:8760/eureka/,http://peer3:8761/eureka/

---
spring:
  profiles: peer2
  application:
    name: eureka-server

server:
  port: 8760


eureka:
  instance:
    hostname: peer2
  client:
    #    registerWithEureka: false
    #    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8759/eureka/,http://peer3:8761/eureka/

---
spring:
  profiles: peer3
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  instance:
    hostname: peer3
  client:
    #    registerWithEureka: false
    #    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8759/eureka/,http://peer2:8760/eureka/
