server:
  port: 8020
eureka:
  instance:
    hostname: eureka-center
    appname: 注册中心
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://test:123456@localhost:8020/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
